export {
  SOCKET_GAP,
  SOCKET_SIZE,
  SOCKET_MARGIN_FROM_EDGE,
  SOCKET_MARGIN_FROM_GROUP,
  MIN_PLATE_HEIGHT,
  MIN_PLATE_WIDTH,
  MAX_PLATE_WIDTH,
  MAX_PLATE_HEIGHT,
  MIN_PLATE_HEIGHT_FOR_SOCKET,
  MIN_PLATE_WIDTH_FOR_SOCKET,
  GAP_BETWEEN_PLATES,
} from "./constants.ts";
